import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#dae2fd',
        'secondary-fixed-dim': '#93ccff',
        'tertiary': '#006947',
        'on-background': '#131b2e',
        'tertiary-fixed-dim': '#4edea3',
        'surface-bright': '#faf8ff',
        'outline': '#6d7a77',
        'inverse-on-surface': '#eef0ff',
        'primary': '#00685f',
        'inverse-surface': '#283044',
        'surface-dim': '#d2d9f4',
        'primary-fixed-dim': '#6bd8cb',
        'primary-container': '#008378',
        'surface': '#faf8ff',
        'on-secondary-fixed': '#001d31',
        'tertiary-fixed': '#6ffbbe',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#005236',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#002113',
        'on-secondary-fixed-variant': '#004b73',
        'tertiary-container': '#00855b',
        'background': '#faf8ff',
        'surface-container': '#eaedff',
        'on-surface-variant': '#3d4947',
        'on-error-container': '#93000a',
        'on-secondary-container': '#00476e',
        'on-primary-container': '#f4fffc',
        'surface-container-lowest': '#ffffff',
        'secondary': '#006398',
        'error': '#ba1a1a',
        'on-tertiary-container': '#f5fff6',
        'primary-fixed': '#89f5e7',
        'secondary-fixed': '#cce5ff',
        'surface-container-highest': '#dae2fd',
        'on-primary-fixed-variant': '#005049',
        'surface-container-high': '#e2e7ff',
        'on-primary': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'outline-variant': '#bcc9c6',
        'surface-tint': '#006a61',
        'inverse-primary': '#6bd8cb',
        'on-tertiary': '#ffffff',
        'secondary-container': '#5bb8fe',
        'on-primary-fixed': '#00201d',
        'on-surface': '#131b2e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter': '1.5rem',
        'gutter-mobile': '1rem',
        'margin': '2rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        'jakarta': ['Plus Jakarta Sans', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}

export default config
